services:
  mysql-dev:
    image: mysql:9.6
    container_name: smart-learning-mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smartlearning-dev

volumes:
  mysql_data:
    
networks:
  smartlearning-dev:
    driver: bridge